#!/bin/bash
# UniPerk Setup Script
# Installs dependencies and generates agent wallet

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTRACTS_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$CONTRACTS_DIR/.env"

echo "🦄 UniPerk Setup"
echo "================"

# 1. Check Foundry installation
echo ""
echo "📦 Checking Foundry..."
if ! command -v forge &> /dev/null; then
    echo "❌ Foundry not found. Installing..."
    curl -L https://foundry.paradigm.xyz | bash
    source ~/.bashrc 2>/dev/null || source ~/.zshrc 2>/dev/null || true
    foundryup
else
    echo "✅ Foundry installed: $(forge --version | head -n 1)"
fi

# 2. Install Solidity dependencies
echo ""
echo "📚 Installing dependencies..."
cd "$CONTRACTS_DIR"
forge install --no-commit 2>/dev/null || echo "Dependencies already installed"
echo "✅ Dependencies ready"

# 3. Compile contracts
echo ""
echo "🔨 Compiling contracts..."
forge build
echo "✅ Contracts compiled"

# 4. Generate agent wallet (if not exists)
echo ""
echo "🔑 Checking agent wallet..."
if [ -f "$ENV_FILE" ] && grep -q "AGENT_PRIVATE_KEY" "$ENV_FILE"; then
    AGENT_ADDRESS=$(grep "AGENT_ADDRESS" "$ENV_FILE" | cut -d '=' -f2)
    echo "✅ Agent wallet exists: $AGENT_ADDRESS"
else
    echo "🆕 Generating new agent wallet..."
    WALLET_OUTPUT=$(cast wallet new)
    
    AGENT_PRIVATE_KEY=$(echo "$WALLET_OUTPUT" | grep "Private key:" | awk '{print $3}')
    AGENT_ADDRESS=$(echo "$WALLET_OUTPUT" | grep "Address:" | awk '{print $2}')
    
    # Append to .env (preserve existing content)
    echo "" >> "$ENV_FILE"
    echo "# Agent Wallet (generated by setup.sh)" >> "$ENV_FILE"
    echo "AGENT_PRIVATE_KEY=$AGENT_PRIVATE_KEY" >> "$ENV_FILE"
    echo "AGENT_ADDRESS=$AGENT_ADDRESS" >> "$ENV_FILE"
    
    # Secure the file
    chmod 600 "$ENV_FILE"
    
    echo "✅ Agent wallet generated:"
    echo "   Address: $AGENT_ADDRESS"
    echo "   Private key saved to: $ENV_FILE"
fi

# 5. Summary
echo ""
echo "================"
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Fund the agent wallet with ETH and USDC"
echo "     Run: ./scripts/fund-agent.sh <amount_eth>"
echo ""
echo "  2. Register agent in AgentRegistry"
echo "     forge script script/RegisterAgent.s.sol --broadcast"
echo ""
echo "  3. (Optional) Deposit to Yellow Nitrolite"
echo "     Run: ./scripts/fund-agent.sh --nitrolite <amount_usdc>"
