#!/bin/bash
# UniPerk - Generate Agent Wallet
# Uses Foundry's cast wallet

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/contracts/.env"

echo "🔑 UniPerk Wallet Setup"
echo "======================="
echo ""

# Check Foundry
if ! command -v cast &> /dev/null; then
    echo "❌ Foundry not installed."
    echo "   Install: curl -L https://foundry.paradigm.xyz | bash && foundryup"
    exit 1
fi

# Check if wallet already exists
if [ -f "$ENV_FILE" ] && grep -q "AGENT_PRIVATE_KEY" "$ENV_FILE"; then
    AGENT_ADDRESS=$(grep "AGENT_ADDRESS" "$ENV_FILE" | cut -d '=' -f2)
    echo "⚠️  Agent wallet already exists: $AGENT_ADDRESS"
    echo ""
    read -p "Generate new wallet? (y/N): " CONFIRM
    if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
        echo "Keeping existing wallet."
        exit 0
    fi
fi

# Generate new wallet
echo "🆕 Generating new agent wallet..."
WALLET_OUTPUT=$(cast wallet new)

AGENT_PRIVATE_KEY=$(echo "$WALLET_OUTPUT" | grep "Private key:" | awk '{print $3}')
AGENT_ADDRESS=$(echo "$WALLET_OUTPUT" | grep "Address:" | awk '{print $2}')

# Create .env if not exists
mkdir -p "$(dirname "$ENV_FILE")"
touch "$ENV_FILE"

# Remove old agent keys if they exist
if [ -f "$ENV_FILE" ]; then
    sed -i '' '/AGENT_PRIVATE_KEY/d' "$ENV_FILE" 2>/dev/null || true
    sed -i '' '/AGENT_ADDRESS/d' "$ENV_FILE" 2>/dev/null || true
    sed -i '' '/# Agent Wallet/d' "$ENV_FILE" 2>/dev/null || true
fi

# Append new wallet
echo "" >> "$ENV_FILE"
echo "# Agent Wallet (generated by setup-wallet.sh)" >> "$ENV_FILE"
echo "AGENT_PRIVATE_KEY=$AGENT_PRIVATE_KEY" >> "$ENV_FILE"
echo "AGENT_ADDRESS=$AGENT_ADDRESS" >> "$ENV_FILE"

# Secure the file
chmod 600 "$ENV_FILE"

echo ""
echo "✅ Agent wallet generated!"
echo ""
echo "   Address: $AGENT_ADDRESS"
echo "   Private key saved to: contracts/.env"
echo ""
echo "Next steps:"
echo "  1. Fund wallet: ./scripts/fund-agent.sh 0.01"
echo "  2. Deploy contracts: ./scripts/deploy.sh"
